In [1]:
library(haven)

In [ ]:
#load Ed Data
meapdata<-read_dta("MEAP93.dta")
head(meapdata)

In [ ]:
#regress test scores on enrollment, total compensation and number of staff
reg2<-lm(math10~enroll + totcomp + staff, data = meapdata)
summary(reg2)

In [ ]:
#regress test scores on log enrollment, log compensation, and log staff
reg3 <-lm(math10~lenroll + ltotcomp + lstaff, data = meapdata)
summary(reg3)

In [ ]:
#use twoyeardataset
twoyeardata<- read_dta("twoyear.dta")
head(twoyeardata)

In [ ]:
#generate regression model
reg4 <- lm(lwage ~ jc + univ + exper, data = twoyeardata)
summary(reg4)

In [9]:
#test for equality of coefficients.  Need "car" library
library(car)
#command linearHypothesis takes the regression object, and then states the model
linearHypothesis(reg4, "jc = univ")

Loading required package: carData

ERROR: Error: object 'reg4' not found

In [ ]:
#alternative: rewrite the model
twoyeardata[,"allschool"]= twoyeardata[,"jc"]+twoyeardata[,"univ"]
reg5 <- lm(lwage ~ jc + allschool + exper, data = twoyeardata)
summary(reg5)

In [2]:
#read in birthweight data
bweight <- read_dta("BWGHT.DTA")
head(bweight)
#regress birthweight on cigs and parity
reg6<-lm(bwght~cigs + parity, data = bweight)
summary(reg6)

  faminc cigtax cigprice bwght fatheduc motheduc parity male white cigs
1 13.5   16.5   122.3    109   12       12       1      1    1     0
2  7.5   16.5   122.3    133    6       12       2      1    0     0
3  0.5   16.5   122.3    129   NA       12       2      0    0     0
4 15.5   16.5   122.3    126   12       12       2      1    0     0
5 27.5   16.5   122.3    134   14       12       2      1    1     0
6  7.5   16.5   122.3    118   12       14       6      1    0     0
  lbwght   bwghtlbs packs lfaminc
1 4.691348 6.8125   0      2.6026897
2 4.890349 8.3125   0      2.0149031
3 4.859812 8.0625   0     -0.6931472
4 4.836282 7.8750   0      2.7408400
5 4.897840 8.3750   0      3.3141861
6 4.770685 7.3750   0      2.0149031

Call:
lm(formula = bwght ~ cigs + parity, data = bweight)

Residuals:
    Min      1Q  Median      3Q     Max
-95.866 -11.866   1.134  13.134 152.134

Coefficients:
             Estimate Std. Error t value Pr(>|t|)
(Intercept) 117.38306    1.12967 103.909  < 2e-16 ***
cigs         -0.52895    0.09054  -5.842 6.41e-09 ***
parity        1.48264    0.60487   2.451   0.0144 *
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 20.09 on 1385 degrees of freedom
Multiple R-squared:  0.02695,	Adjusted R-squared:  0.02555
F-statistic: 19.18 on 2 and 1385 DF,  p-value: 6.074e-09

In [3]:

reg9 <- lm(bwght~cigs + parity + motheduc + fatheduc, data = bweight)
summary(reg9)

Call:
lm(formula = bwght ~ cigs + parity + motheduc + fatheduc, data = bweight)

Residuals:
    Min      1Q  Median      3Q     Max
-96.139 -11.935   0.778  12.649 151.255

Coefficients:
            Estimate Std. Error t value Pr(>|t|)
(Intercept) 113.7365     3.6950  30.782  < 2e-16 ***
cigs         -0.6059     0.1102  -5.497 4.72e-08 ***
parity        1.7650     0.6596   2.676  0.00756 **
motheduc     -0.2764     0.3141  -0.880  0.37901
fatheduc      0.5795     0.2740   2.115  0.03464 *
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 19.8 on 1186 degrees of freedom
  (197 observations deleted due to missingness)
Multiple R-squared:  0.03684,	Adjusted R-squared:  0.03359
F-statistic: 11.34 on 4 and 1186 DF,  p-value: 4.913e-09

In [4]:
#only keep observations where all variables are not missing for F calculation
bweight<- subset(bweight, is.na(fatheduc) == F &is.na(motheduc)== F)
#regress birthweight on cigarette consumption,  birth order, and family income
reg7<- lm(bwght ~ cigs + parity + faminc, data = bweight)
summary(reg7)

Call:
lm(formula = bwght ~ cigs + parity + faminc, data = bweight)

Residuals:
    Min      1Q  Median      3Q     Max
-95.811 -11.552   0.524  12.739 150.848

Coefficients:
             Estimate Std. Error t value Pr(>|t|)
(Intercept) 115.46993    1.65590  69.733  < 2e-16 ***
cigs         -0.59785    0.10877  -5.496 4.74e-08 ***
parity        1.83227    0.65754   2.787  0.00541 **
faminc        0.06706    0.03239   2.070  0.03865 *
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 19.8 on 1187 degrees of freedom
Multiple R-squared:  0.03642,	Adjusted R-squared:  0.03398
F-statistic: 14.95 on 3 and 1187 DF,  p-value: 1.472e-09

In [5]:
#include family background controls
reg8 <- lm(bwght ~ cigs + parity + faminc + motheduc + fatheduc, data = bweight)
summary(reg8)

Call:
lm(formula = bwght ~ cigs + parity + faminc + motheduc + fatheduc,
    data = bweight)

Residuals:
    Min      1Q  Median      3Q     Max
-95.796 -11.960   0.643  12.679 150.879

Coefficients:
             Estimate Std. Error t value Pr(>|t|)
(Intercept) 114.52433    3.72845  30.716  < 2e-16 ***
cigs         -0.59594    0.11035  -5.401 8.02e-08 ***
parity        1.78760    0.65941   2.711  0.00681 **
faminc        0.05604    0.03656   1.533  0.12559
motheduc     -0.37045    0.31986  -1.158  0.24702
fatheduc      0.47239    0.28264   1.671  0.09492 .
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 19.79 on 1185 degrees of freedom
Multiple R-squared:  0.03875,	Adjusted R-squared:  0.03469
F-statistic: 9.553 on 5 and 1185 DF,  p-value: 5.986e-09

In [6]:
#calculate sums of squared residuals
#unrestricted model
SSRU<-sum(resid(reg8)^2)
SSRU
#restricted model
SSRR<-sum(resid(reg7)^2)
SSRR
#identify n
n <- nobs(reg8)
n

[1] 464041.1

[1] 465166.8

[1] 1191

In [7]:
#generate F test
F1<- ((SSRR-SSRU)/2)/(SSRU/(n-5-1))
F1

[1] 1.437269

In [8]:
#R-squared calculation
#Pull unrestricted R-squared from regression output
Rsq_u <-summary(reg8)$r.squared
Rsq_u
#Pull restricted R-squared from regression output
Rsq_r <-summary(reg7)$r.squared
Rsq_r
F2 <- ((Rsq_u-Rsq_r)/2)/((1-Rsq_u)/(n-5-1))
F2

[1] 0.03874818

[1] 0.03641641

[1] 1.437269

In [10]:
#use linearHypothesis test to generate p-value
F3 <- linearHypothesis(reg8,c("motheduc = 0", "fatheduc = 0"))
F3

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 1187   465166.8 NA       NA        NA        NA
2 1185   464041.1  2 1125.657  1.437269 0.2379896